//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwnCloud.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OwnCloud.Resource.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete &quot;{0:g}&quot; account?.
        /// </summary>
        public static string AccountsPage_Confirm_Delete {
            get {
                return ResourceManager.GetString("AccountsPage_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string AccountsPage_Confirm_Delete_Caption {
            get {
                return ResourceManager.GetString("AccountsPage_Confirm_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ApplicationBarButton_Add {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose account.
        /// </summary>
        public static string ApplicationBarButton_ChooseAccount {
            get {
                return ResourceManager.GetString("ApplicationBarButton_ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string ApplicationBarButton_Lock {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ApplicationBarButton_Save {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string ApplicationBarButton_Unlock {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ApplicationBarButton_View {
            get {
                return ResourceManager.GetString("ApplicationBarButton_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is before the start date. Please fix this..
        /// </summary>
        public static string AppointmentPage_WrongDate {
            get {
                return ResourceManager.GetString("AppointmentPage_WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnCloud Client.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Settings.
        /// </summary>
        public static string CalendarMonthPage_ListCalendars {
            get {
                return ResourceManager.GetString("CalendarMonthPage_ListCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string CalendarMonthPage_ReloadEvents {
            get {
                return ResourceManager.GetString("CalendarMonthPage_ReloadEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owncloud calendars.
        /// </summary>
        public static string CalendarMonthPage_Title {
            get {
                return ResourceManager.GetString("CalendarMonthPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string EditAccountPage_AddAccount {
            get {
                return ResourceManager.GetString("EditAccountPage_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous access.
        /// </summary>
        public static string EditAccountPage_Anonymous {
            get {
                return ResourceManager.GetString("EditAccountPage_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while checking connection....
        /// </summary>
        public static string EditAccountPage_CheckingConnection {
            get {
                return ResourceManager.GetString("EditAccountPage_CheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAV-structure was not recognized. Please check the server paths.
        ///Failed path: {0}
        ///Server Answer: {1}.
        /// </summary>
        public static string EditAccountPage_CheckingConnection_DAVTestFailed {
            get {
                return ResourceManager.GetString("EditAccountPage_CheckingConnection_DAVTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to &quot;{0:g}://{1:g}&quot; failed.
        ///
        ///Would you like to add this account anyway?.
        /// </summary>
        public static string EditAccountPage_Confirm_Store {
            get {
                return ResourceManager.GetString("EditAccountPage_Confirm_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string EditAccountPage_Confirm_Store_Caption {
            get {
                return ResourceManager.GetString("EditAccountPage_Confirm_Store_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to &quot;{0:g}&quot; was rejected by your phone as the security certificate was not valid or self signed. Please import the certificate into the phone and try again.
        ///
        ///Certifcate: {1:g}
        ///Valid After: {2:g}
        ///Valid To: {3:g}.
        /// </summary>
        public static string EditAccountPage_Connection_Rejected {
            get {
                return ResourceManager.GetString("EditAccountPage_Connection_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string EditAccountPage_Connection_Rejected_Caption {
            get {
                return ResourceManager.GetString("EditAccountPage_Connection_Rejected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string EditAccountPage_EditAccount {
            get {
                return ResourceManager.GetString("EditAccountPage_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EditAccountPage_Password {
            get {
                return ResourceManager.GetString("EditAccountPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string EditAccountPage_Server {
            get {
                return ResourceManager.GetString("EditAccountPage_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EditAccountPage_Username {
            get {
                return ResourceManager.GetString("EditAccountPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this page was no user id given.
        /// </summary>
        public static string Exception_NoUserID {
            get {
                return ResourceManager.GetString("Exception_NoUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t fetch the file list from target server: Permission denied..
        /// </summary>
        public static string FetchFile_Unauthorized {
            get {
                return ResourceManager.GetString("FetchFile_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t fetch the file list from target server. Maybe there is a temporary problem..
        /// </summary>
        public static string FetchFile_Unexpected_Result {
            get {
                return ResourceManager.GetString("FetchFile_Unexpected_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File_Type_Default {
            get {
                return ResourceManager.GetString("File_Type_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string FileItem_Up {
            get {
                return ResourceManager.GetString("FileItem_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string MainPage_Accounts {
            get {
                return ResourceManager.GetString("MainPage_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts found..
        /// </summary>
        public static string MainPage_AccountsText {
            get {
                return ResourceManager.GetString("MainPage_AccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        public static string MainPage_CalendarHeader {
            get {
                return ResourceManager.GetString("MainPage_CalendarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MainPage_Files {
            get {
                return ResourceManager.GetString("MainPage_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MainPage_Info {
            get {
                return ResourceManager.GetString("MainPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string MainPage_PinToStart {
            get {
                return ResourceManager.GetString("MainPage_PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Files.
        /// </summary>
        public static string MainPage_Remote_Files {
            get {
                return ResourceManager.GetString("MainPage_Remote_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an account to browse trough or select files to sync..
        /// </summary>
        public static string MainPage_Remote_Files_Text {
            get {
                return ResourceManager.GetString("MainPage_Remote_Files_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free disk space (device).
        /// </summary>
        public static string MainPage_Status_FreeDiskSpace {
            get {
                return ResourceManager.GetString("MainPage_Status_FreeDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol {0:g} not supported..
        /// </summary>
        public static string Model_Account_Protocol_Unsupported {
            get {
                return ResourceManager.GetString("Model_Account_Protocol_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server domain cannot be empty!.
        /// </summary>
        public static string Model_Account_ServerDomain_Empty {
            get {
                return ResourceManager.GetString("Model_Account_ServerDomain_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be empty..
        /// </summary>
        public static string Model_Account_Username_Empty {
            get {
                return ResourceManager.GetString("Model_Account_Username_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename cannot be empty!.
        /// </summary>
        public static string Model_File_Filename_Empty {
            get {
                return ResourceManager.GetString("Model_File_Filename_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to &quot;{0:g}&quot;: {1:g}..
        /// </summary>
        public static string Net_StreamSocket_ConnectFailed {
            get {
                return ResourceManager.GetString("Net_StreamSocket_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string RemoteFilesPage_DetailView {
            get {
                return ResourceManager.GetString("RemoteFilesPage_DetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string RemoteFilesPage_TileView {
            get {
                return ResourceManager.GetString("RemoteFilesPage_TileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string SettingsPage_Accounts {
            get {
                return ResourceManager.GetString("SettingsPage_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string SettingsPage_AddAccount {
            get {
                return ResourceManager.GetString("SettingsPage_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add an account, tap&quot;Add&quot;. To edit or remove, first tap on &quot;Lock&quot; then tap on the account to edit. Move the account to the right until the account will be completely disappear to remove it..
        /// </summary>
        public static string SettingsPage_AddAccount_Help {
            get {
                return ResourceManager.GetString("SettingsPage_AddAccount_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable file preview..
        /// </summary>
        public static string SettingsPage_EnableFilePreview {
            get {
                return ResourceManager.GetString("SettingsPage_EnableFilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a tiny preview of local and remote files..
        /// </summary>
        public static string SettingsPage_EnableFilePreviewSubText {
            get {
                return ResourceManager.GetString("SettingsPage_EnableFilePreviewSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files on Cloud Storage if I delete files on the local device..
        /// </summary>
        public static string SettingsPage_EnableRemoteDeleting {
            get {
                return ResourceManager.GetString("SettingsPage_EnableRemoteDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only refresh remote view if I am connected to WLAN..
        /// </summary>
        public static string SettingsPage_EnableRemoteFilePreviewWLANOnly {
            get {
                return ResourceManager.GetString("SettingsPage_EnableRemoteFilePreviewWLANOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip remote files which are greater than amount KB below:.
        /// </summary>
        public static string SettingsPage_EnableSkipRemoteFiles {
            get {
                return ResourceManager.GetString("SettingsPage_EnableSkipRemoteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show phone status bar..
        /// </summary>
        public static string SettingsPage_ShowPhoneStatusBar {
            get {
                return ResourceManager.GetString("SettingsPage_ShowPhoneStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnCloud Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Tile_KalendarTitle {
            get {
                return ResourceManager.GetString("Tile_KalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Tile_RemoteFileTitle {
            get {
                return ResourceManager.GetString("Tile_RemoteFileTitle", resourceCulture);
            }
        }
    }
}
