//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwnCloud.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OwnCloud.Resource.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to delete &quot;{0:g}&quot; account? ähnelt.
        /// </summary>
        public static string AccountsPage_Confirm_Delete {
            get {
                return ResourceManager.GetString("AccountsPage_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove account ähnelt.
        /// </summary>
        public static string AccountsPage_Confirm_Delete_Caption {
            get {
                return ResourceManager.GetString("AccountsPage_Confirm_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string ApplicationBarButton_Add {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string ApplicationBarButton_Save {
            get {
                return ResourceManager.GetString("ApplicationBarButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OwnCloud Client ähnelt.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar Settings ähnelt.
        /// </summary>
        public static string CalendarMonthPage_ListCalendars {
            get {
                return ResourceManager.GetString("CalendarMonthPage_ListCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload ähnelt.
        /// </summary>
        public static string CalendarMonthPage_ReloadEvents {
            get {
                return ResourceManager.GetString("CalendarMonthPage_ReloadEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owncloud calendars ähnelt.
        /// </summary>
        public static string CalendarMonthPage_Title {
            get {
                return ResourceManager.GetString("CalendarMonthPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory ähnelt.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add account ähnelt.
        /// </summary>
        public static string EditAccountPage_AddAccount {
            get {
                return ResourceManager.GetString("EditAccountPage_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anonymous access ähnelt.
        /// </summary>
        public static string EditAccountPage_Anonymous {
            get {
                return ResourceManager.GetString("EditAccountPage_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CalDAV path ähnelt.
        /// </summary>
        public static string EditAccountPage_CalDAVPath {
            get {
                return ResourceManager.GetString("EditAccountPage_CalDAVPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait while checking connection... ähnelt.
        /// </summary>
        public static string EditAccountPage_CheckingConnection {
            get {
                return ResourceManager.GetString("EditAccountPage_CheckingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection to &quot;{0:g}://{1:g}&quot; failed.
        ///
        ///Would you like to add this account anyway? ähnelt.
        /// </summary>
        public static string EditAccountPage_Confirm_Store {
            get {
                return ResourceManager.GetString("EditAccountPage_Confirm_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection failed ähnelt.
        /// </summary>
        public static string EditAccountPage_Confirm_Store_Caption {
            get {
                return ResourceManager.GetString("EditAccountPage_Confirm_Store_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection to &quot;{0:g}&quot; was rejected by your phone as the security certificate was not valid or self signed. Please import the certificate into the phone and try again.
        ///
        ///Certifcate: {1:g}
        ///Valid After: {2:g}
        ///Valid To: {3:g} ähnelt.
        /// </summary>
        public static string EditAccountPage_Connection_Rejected {
            get {
                return ResourceManager.GetString("EditAccountPage_Connection_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection failed ähnelt.
        /// </summary>
        public static string EditAccountPage_Connection_Rejected_Caption {
            get {
                return ResourceManager.GetString("EditAccountPage_Connection_Rejected_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit account ähnelt.
        /// </summary>
        public static string EditAccountPage_EditAccount {
            get {
                return ResourceManager.GetString("EditAccountPage_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string EditAccountPage_Password {
            get {
                return ResourceManager.GetString("EditAccountPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host ähnelt.
        /// </summary>
        public static string EditAccountPage_Server {
            get {
                return ResourceManager.GetString("EditAccountPage_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string EditAccountPage_Username {
            get {
                return ResourceManager.GetString("EditAccountPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebDAV path ähnelt.
        /// </summary>
        public static string EditAccountPage_WebDAVPath {
            get {
                return ResourceManager.GetString("EditAccountPage_WebDAVPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For this page was no user id given ähnelt.
        /// </summary>
        public static string Exception_NoUserID {
            get {
                return ResourceManager.GetString("Exception_NoUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t fetch the file list from target server. Maybe there is a temporary problem. ähnelt.
        /// </summary>
        public static string FetchFile_Unexpected_Result {
            get {
                return ResourceManager.GetString("FetchFile_Unexpected_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string File_Type_Default {
            get {
                return ResourceManager.GetString("File_Type_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accounts ähnelt.
        /// </summary>
        public static string MainPage_Accounts {
            get {
                return ResourceManager.GetString("MainPage_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage your OwnCloud accounts here. ähnelt.
        /// </summary>
        public static string MainPage_AccountsText {
            get {
                return ResourceManager.GetString("MainPage_AccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendars ähnelt.
        /// </summary>
        public static string MainPage_CalendarHeader {
            get {
                return ResourceManager.GetString("MainPage_CalendarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files ähnelt.
        /// </summary>
        public static string MainPage_Files {
            get {
                return ResourceManager.GetString("MainPage_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string MainPage_Info {
            get {
                return ResourceManager.GetString("MainPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin to start ähnelt.
        /// </summary>
        public static string MainPage_PinToStart {
            get {
                return ResourceManager.GetString("MainPage_PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote Files ähnelt.
        /// </summary>
        public static string MainPage_Remote_Files {
            get {
                return ResourceManager.GetString("MainPage_Remote_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select an account to browse trough or select files to sync. ähnelt.
        /// </summary>
        public static string MainPage_Remote_Files_Text {
            get {
                return ResourceManager.GetString("MainPage_Remote_Files_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free disk space (device) ähnelt.
        /// </summary>
        public static string MainPage_Status_FreeDiskSpace {
            get {
                return ResourceManager.GetString("MainPage_Status_FreeDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protocol {0:g} not supported. ähnelt.
        /// </summary>
        public static string Model_Account_Protocol_Unsupported {
            get {
                return ResourceManager.GetString("Model_Account_Protocol_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server domain cannot be empty! ähnelt.
        /// </summary>
        public static string Model_Account_ServerDomain_Empty {
            get {
                return ResourceManager.GetString("Model_Account_ServerDomain_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username should not be empty. ähnelt.
        /// </summary>
        public static string Model_Account_Username_Empty {
            get {
                return ResourceManager.GetString("Model_Account_Username_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename cannot be empty! ähnelt.
        /// </summary>
        public static string Model_File_Filename_Empty {
            get {
                return ResourceManager.GetString("Model_File_Filename_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot connect to &quot;{0:g}&quot;: {1:g}. ähnelt.
        /// </summary>
        public static string Net_StreamSocket_ConnectFailed {
            get {
                return ResourceManager.GetString("Net_StreamSocket_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string RemoteFilesPage_DetailView {
            get {
                return ResourceManager.GetString("RemoteFilesPage_DetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string RemoteFilesPage_TileView {
            get {
                return ResourceManager.GetString("RemoteFilesPage_TileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accounts ähnelt.
        /// </summary>
        public static string SettingsPage_Accounts {
            get {
                return ResourceManager.GetString("SettingsPage_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Account ähnelt.
        /// </summary>
        public static string SettingsPage_AddAccount {
            get {
                return ResourceManager.GetString("SettingsPage_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To add an account simply tap &quot;Add&quot;. To edit, tap on the account. To delete an account, drag the account to the right till it disappears. ähnelt.
        /// </summary>
        public static string SettingsPage_AddAccount_Help {
            get {
                return ResourceManager.GetString("SettingsPage_AddAccount_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OwnCloud Settings ähnelt.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar ähnelt.
        /// </summary>
        public static string Tile_KalendarTitle {
            get {
                return ResourceManager.GetString("Tile_KalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files ähnelt.
        /// </summary>
        public static string Tile_RemoteFileTitle {
            get {
                return ResourceManager.GetString("Tile_RemoteFileTitle", resourceCulture);
            }
        }
    }
}
